import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Navbar from '../components/navBar'
import About from '../components/About'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
import Contact from '../components/Contact'

export default function Home() {
  return (
    <div className={styles.container}>
      <div className='scroll-smooth'>
        <Head>
          <title>{`Devin's Portfolio`}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
          <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet" />  
        </Head>
        <Navbar />
        {/* useRef + scrolling */}
        <p className='text-xl mt-10 text-4xl italic font-bold'>Devin Lynch</p>

        <About />

        <Skills />

        <Projects />

        <Contact />
      </div>
    </div>
  )
}
